delete from public.post_upvotes a
using public.post_upvotes b
where a.id > b.id
  and a.post_id = b.post_id
  and a.user_id = b.user_id;

create unique index if not exists post_upvotes_post_id_user_id_key
  on public.post_upvotes(post_id, user_id);

create table if not exists public.renders_wallpaper_upvotes (
  id bigint generated by default as identity primary key,
  render_id bigint not null references public.renders_wallpapers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint renders_wallpaper_upvotes_render_user_key unique (render_id, user_id)
);

alter table public.renders_wallpaper_upvotes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_upvotes'
      and policyname = 'renders_wallpaper_upvotes_select_all'
  ) then
    create policy renders_wallpaper_upvotes_select_all
      on public.renders_wallpaper_upvotes
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_upvotes'
      and policyname = 'renders_wallpaper_upvotes_insert_own'
  ) then
    create policy renders_wallpaper_upvotes_insert_own
      on public.renders_wallpaper_upvotes
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_upvotes'
      and policyname = 'renders_wallpaper_upvotes_delete_own_or_admin'
  ) then
    create policy renders_wallpaper_upvotes_delete_own_or_admin
      on public.renders_wallpaper_upvotes
      for delete
      using (
        auth.uid() = user_id
        or exists (
          select 1 from public.profiles
          where profiles.id = auth.uid()
            and profiles.is_admin = true
        )
      );
  end if;
end $$;

create table if not exists public.game_asset_upvotes (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.game_assets_uploads(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint game_asset_upvotes_asset_user_key unique (asset_id, user_id)
);

alter table public.game_asset_upvotes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'game_asset_upvotes'
      and policyname = 'game_asset_upvotes_select_all'
  ) then
    create policy game_asset_upvotes_select_all
      on public.game_asset_upvotes
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'game_asset_upvotes'
      and policyname = 'game_asset_upvotes_insert_own'
  ) then
    create policy game_asset_upvotes_insert_own
      on public.game_asset_upvotes
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'game_asset_upvotes'
      and policyname = 'game_asset_upvotes_delete_own_or_admin'
  ) then
    create policy game_asset_upvotes_delete_own_or_admin
      on public.game_asset_upvotes
      for delete
      using (
        auth.uid() = user_id
        or exists (
          select 1 from public.profiles
          where profiles.id = auth.uid()
            and profiles.is_admin = true
        )
      );
  end if;
end $$;