create table if not exists public.renders_wallpaper_comments (
  id bigint generated by default as identity primary key,
  render_id bigint not null references public.renders_wallpapers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.renders_wallpaper_comments enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_comments'
      and policyname = 'render_comments_select_all'
  ) then
    create policy render_comments_select_all
      on public.renders_wallpaper_comments
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_comments'
      and policyname = 'render_comments_insert_own'
  ) then
    create policy render_comments_insert_own
      on public.renders_wallpaper_comments
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'renders_wallpaper_comments'
      and policyname = 'render_comments_delete_own_or_admin'
  ) then
    create policy render_comments_delete_own_or_admin
      on public.renders_wallpaper_comments
      for delete
      using (
        auth.uid() = user_id
        or exists (
          select 1 from public.profiles
          where profiles.id = auth.uid()
            and profiles.is_admin = true
        )
      );
  end if;
end $$;